name: Letsencrypt Nginx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t nginx-proxy .
      - name: Tags
        run: |
          docker tag nginx-proxy ${{ secrets.DOCKER_USER }}/nginx-proxy:${{ github.sha }}
          docker tag nginx-proxy ${{ secrets.DOCKER_USER }}/nginx-proxy:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/nginx-proxy:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/nginx-proxy:latest
